spring.datasource.url=jdbc:postgresql://localhost:5432/local_service_booking

spring.datasource.username=amit.kumar

spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

jwt.secret=local-service-booking-development-secret-key-2026
jwt.expiration=86400000